$schema: "https://moonrepo.dev/schemas/tasks.json"

tasks:
  test:
    description: Run tests with Vitest
    command: 'vitest'
    args: ['run']
    inputs:
      - '@globs(sources)'
      - '@globs(tests)'
      - 'vitest.config.*'
    options:
      cache: local