$schema: "https://moonrepo.dev/schemas/tasks.json"

inheritedBy:
  tags: ['astro']

tasks:
  build:
    description: Build the Astro project for production
    command: 'astro'
    args: ['build']
    inputs:
      - '@globs(sources)'
      - 'astro.config.*'
      - 'package.json'
    outputs:
      - 'dist'

  dev:
    description: Start the Astro development server
    command: 'astro'
    args: ['dev']
    options:
      cache: local