$schema: "https://moonrepo.dev/schemas/tasks.json"

tasks:
  build:
    description: Build the library with Packemon
    script: 'packemon pack --addEngines --addExports --declaration'
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.*.json'
    outputs:
      - 'lib'
      - 'esm'
