$schema: "https://moonrepo.dev/schemas/tasks.json"

inheritedBy:
  tags: ['vite']

tasks:
  build:
    description: Build the Vite project for production
    command: 'vite'
    args: ['build']
    inputs:
      - '@globs(sources)'
      - 'vite.config.*'
      - 'package.json'
    outputs:
      - 'dist'

  dev:
    description: Start the Vite development server
    command: 'vite'
    args: ['dev']
    options:
      cache: local
