$schema: "https://moonrepo.dev/schemas/tasks.json"

inheritedBy:
  tags: ['packemon']

tasks:
  build:
    description: Build the library with Packemon
    command: 'packemon'
    args: ['pack', '--addEngines', '--addExports', '--declaration']
    inputs:
      - '@globs(sources)'
      - 'package.json'
      - 'tsconfig.*.json'
    outputs:
      - 'lib'
      - 'esm'
